version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=Co138Ji4eZp1E7YL
      - DB_NAME=postgres
      - DB_PORT=5432
      - DB_DSN=host=db user=postgres password=Co138Ji4eZp1E7YL dbname=postgres port=5432 sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Co138Ji4eZp1E7YL
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
