name: Build and Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group   
    steps:
    - uses: actions/checkout@v4  
    - uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Build and Deploy Docker Image
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        DB_DSN: ${{ secrets.DB_DSN }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_PORT: ${{ secrets.DB_PORT }}
      run: |
        docker build \
          --build-arg DB_DSN="${DB_DSN}" \
          --build-arg DB_HOST="${DB_HOST}" \
          --build-arg DB_USER="${DB_USER}" \
          --build-arg DB_PASSWORD="${DB_PASSWORD}" \
          --build-arg DB_NAME="${DB_NAME}" \
          --build-arg DB_PORT="${DB_PORT}" \
          -t startup:latest .

    - name: Deploy to Fly.io
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      run: |
        flyctl deploy --remote-only
